---
title: "Sql Lesson Sept 14"
output: html_document
---

library(Lahman)
library(sqldf)

Group By:
  
1.
```{r}
query<-"SELECT playerID, sum(HR) FROM Batting 
WHERE playerID='ruthba01'
GROUP BY playerID"

sqldf(query)
```

#----------

Aggregation:
  
1.
```{r}
query<-"SELECT playerID, sum(HR) FROM Batting
Group BY playerID
HAVING sum(HR)>=600
ORDER BY sum(HR) DESC"

sqldf(query)

```


2.
```{r}
query<-"SELECT playerID, avg(HR) FROM Batting
GROUP BY playerID
HAVING avg(HR)>30
ORDER BY avg(HR) DESC"

sqldf(query)
```

#------------

joins:
  
1.
```{r}
query<-"SELECT nameFirst,nameLast,yearID,teamID,HR 
FROM Batting INNER JOIN Master
ON Batting.playerID=Master.playerID
WHERE Batting.playerID='ruthba01'"

sqldf(query)
```


2.
```{r}
query<-"SELECT nameFirst,nameLast,teamID,yearID, HR
FROM Batting INNER JOIN Master
ON Batting.playerID=Master.playerID
WHERE HR>50
ORDER BY HR DESC"

sqldf(query)
```


3.
```{r}
query<-"SELECT playerID,name,Batting.yearID,Batting.HR
FROM Batting INNER JOIN Teams
ON Batting.teamID=Teams.teamID AND Batting.yearID=Teams.yearID
WHERE playerID='ruthba01'"

sqldf(query)
```